# Comprehensive NSE + BSE stock list for UI dropdown
# Covers NIFTY 500 + popular midcaps + known BSE stocks
# Users can type to filter (Streamlit selectbox has search built-in)

VALID_TICKERS = [
    # NIFTY 50
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "ITC", "SBIN",
    "KOTAKBANK", "AXISBANK", "LT", "HINDUNILVR", "BAJFINANCE",
    "MARUTI", "ONGC", "HCLTECH", "SUNPHARMA", "ASIANPAINT", "NTPC",
    "TITAN", "ULTRACEMCO", "TATAMOTORS", "M&M", "POWERGRID", "WIPRO",
    "BAJAJFINSV", "NESTLEIND", "COALINDIA", "TECHM", "JSWSTEEL", "ADANIPORTS",
    "HINDALCO", "GRASIM", "TATASTEEL", "INDUSINDBK",
    "SBILIFE", "HDFCLIFE", "BRITANNIA", "BAJAJ-AUTO", "APOLLOHOSP",
    "DRREDDY", "CIPLA", "EICHERMOT", "DIVISLAB", "TATACONSUM", "HEROMOTOCO",
    "UPL", "BPCL", "SHRIRAMFIN", "ADANIENT",
    # NIFTY NEXT 50 / NIFTY 100
    "PIDILITIND", "BOSCHLTD", "TVSMOTOR", "RECLTD", "PFC", "AUBANK", "BEL",
    "SRF", "INDIGO", "VEDL", "ZEEL", "HAVELLS", "DABUR", "BERGEPAINT",
    "MUTHOOTFIN", "TORNTPHARM", "LUPIN", "CADILAHC", "AUROPHARMA",
    "BIOCON", "ABBOTINDIA", "PFIZER", "GLAXO",
    "COLPAL", "MARICO", "GODREJCP", "GODREJPROP", "EMAMILTD",
    "PAGEIND", "WHIRLPOOL", "BATAINDIA",
    "SIEMENS", "ABB", "CUMMINSIND", "THERMAX", "BEL",
    "HAL", "BDL", "BEML", "BHEL", "IRCTC", "IRFC", "RVNL", "RAILTEL",
    "CONCOR", "NMDC", "SAIL", "MOIL",
    "BANKBARODA", "PNB", "CANBK", "UNIONBANK", "BANKINDIA", "IOB", "CENTRALBANK",
    "FEDERALBNK", "IDFCFIRSTB", "RBLBANK", "BANDHANBNK", "DCBBANK", "KTKBANK",
    "KARURVYSYA", "LAKSHVILAS",
    "MCDOWELL-N", "UNITEDSPIRITS", "RADICO",
    "JUBLFOOD", "DEVYANI", "WESTLIFE", "SAPPHIRE",
    "DMART", "TRENT", "VMART", "NYKAA", "ZOMATO", "SWIGGY",
    "PAYTM", "POLICYBZR", "CARTRADE",
    "IREDA", "SJVN", "NHPC", "THDCIL",
    "ADANIGREEN", "ADANITRANS", "ADANIPOWER", "ATGL",
    "TORNTPOWER", "TATAPOWER", "CESC", "JSPL",
    "HINDCOPPER", "NATIONALUM", "HINDZINC",
    "CHOLAFIN", "BAJAJHLDNG", "ICICIlombard", "ICICIGI", "STARHEALTH",
    "NIACL", "KANSAINER", "ORIENTCEM",
    "ASHOKLEY", "FORCEMOT", "ESCORTS", "TIINDIA", "MOTHERSON", "MINDA",
    "BALKRISIND", "MRF", "CEATLTD", "APOLLOTYRE",
    "DEEPAKNITR", "TATACHEM", "PIDILITIND", "AARTIIND",
    "NAVINFLUOR", "FLUOROCHEM", "NOCIL", "BALMLAWRIE",
    "LALPATHLAB", "METROPOLIS", "THYROCARE", "KRSNAA",
    "FORTIS", "NARAYANA", "KIMS", "MAXHEALTH", "RAINBOW",
    "ZYDUSLIFE", "ALKEM", "GLENMARK", "IPCALAB", "GRANULES",
    "JUBILANT", "SYNGENE", "DIVI",
    "HFCL", "STERLITE", "TATACOMM", "BHARTIARTL", "VODAIDEA", "IDEA",
    "MTNL", "BSNL",
    "INFOEDGE", "JUSTDIAL", "MATRIMONY", "AFFLE",
    "COFORGE", "MPHASIS", "PERSISTENT", "LTTS", "HEXAWARE",
    "RATEGAIN", "NEWGEN", "ZENSAR", "MASTEK", "CSS",
    "TATAELXSI", "KPITTECH", "SASKEN",
    "DELHIVERY", "TBO", "INDIAMART", "SHOPCLUES",
    "SOLARINDS", "PREMIER", "MAPMYINDIA",
    "LODHA", "PRESTIGE", "BRIGADE", "SOBHA", "OBEROI", "SUNTECK", "NCLIND",
    "PHOENIXLTD", "INDIABULLS",
    "SBICARD", "BAJFINANCE", "MANAPPURAM", "IIFL", "MAS",
    "LIChousing", "REPCO", "CAN_FIN",
    "VEDL", "TATASTLBSL", "JINDALSTEL", "GAIL",
    "PETRONET", "MGL", "IGL", "GSPL",
    "EXIDEIND", "AMARAJABAT", "LUMINOUS",
    "PVRINOX", "INOX", "MOVIETIME",
    "HATSUN", "HERITGFOOD", "PARAG", "PRABHAT",
    "RELAXO", "LIBERTY", "BATA", "VIP",
    "VGUARD", "ORIENTELEC", "HAVELLS", "CROMPTON", "POLYCAB",
    "FINOLEX", "KEIIND",
    "ASAHIINDIA", "BOROSIL", "SAINT-GOBAIN",
    "RAYMOND", "WELSPUN", "TRIDENT", "ARVIND", "KPR",
    "SCHNEIDER", "HITACHIEM", "VOLTAS", "BLUESTAR",
    "MPHASIS", "INTELLECT", "OFSS", "CYIENT",
    "ASTRAL", "SUPREMIND", "PRINCEPIPE",
    "DELHIVERY", "REDINGTON", "IGATE",
    "ELGIEQUIP", "GRINDWELL", "TIMKEN", "SKF",
    "NAUKRI", "CAREERPT",
    "TANLA", "ROUTE", "ONMOBILE",
    "GREENPLY", "CENTURY", "SHANKARA",
    "KPRMILL", "VARDHMAN", "GOKEX",
    "GPPL", "ADANIPORTS", "ESABINDIA",
    "GILLETTE", "PFIZER", "MERCK",
    "HINDPETRO", "MRPL", "CHENNPETRO", "AEGISLOG",
    "DEEPAKFERT", "RCF", "CHAMBALFERT", "COROMANDEL",
    "PIIND", "BALAMINES", "TEAMLEASE",
    "QUESS", "SIS", "CARERATING", "CRISIL", "ICRA",
    "ULTRATECH", "RAMCOCEM", "JKCEMENT", "HEIDELBERG",
    "WHIRLPOOL", "BAJAJCON", "EMAMILTD",
    "SANOFI", "NATCOPHARM", "SUNPHARMA", "CONCORD",
    "TCIEXPRESS", "BLUEDART", "GICRE", "NIIT",
    "DELTACORP", "PAISALO", "EDELWEISS",
    "GABRIEL", "MINDAIND", "SUBROS",
    "NCC", "KEC", "KALPATPOWR", "TECHNO", "PATELENG",
    "AHLUCONT", "CAPACITE", "PDSL",
    "HAPPYFORGE", "MCX", "BSE", "CDSL", "CAMS",
    "GPILLTD", "SAREGAMA", "TIPS", "EROSMEDI",
    "FINEORG", "SUVENPHAR", "NEULANDLAB",
    "LAXMIMACH", "JYOTHYLAB", "HGINFRA",
    "GPPL", "SUNTV", "TVTODAY", "NDTV", "DBCORP",
    "PSPPROJECT", "APLAPOLLO",
    "JINDALSAW", "JSPL", "WELCORP", "MAAN",
    "GREAVESCOT", "ATLAS", "KIRLOSKAR",
    "CENTURYPLY", "GREENPAN", "MAYURESH",
    "HONAUT", "SCHAEFFLER", "PFIZER", "WYETH",
    "SUPRAJIT", "SANDHAR", "SETCO",
    "ORIENTCARBO", "GRAPHITE", "HEG", "SHIVALIK",
    "TATAINVEST", "GAMMONIND", "WOCKPHARMA",
    "STARCEMENT", "BIRLAMONEY", "BFLUS",
    "CHOICEIN", "GEOJITFSL", "MOTILALOFS", "5PAISA",
    "EQUITASBNK", "SURYODAY", "UTKARSHBNK",
    "AARTIDRUGS", "MARKSANS", "SMSPHARMA",
    "GLAND", "ANURAS", "MANKIND",
    "CAMPUSACT", "DELHERY", "ALLCARGO",
    "HFCL", "RAILTEL", "RITES",
    "INDIACEM", "HEMIPROP", "PENLAND",
    "NAZARA", "PLAYGAMES24", "ONLINEGAME",
    "Custom...",
]

# Remove duplicates while preserving order
_seen = set()
_deduped = []
for t in VALID_TICKERS:
    if t not in _seen:
        _seen.add(t)
        _deduped.append(t)
VALID_TICKERS = _deduped

TICKER_NAMES = {
    # NIFTY 50 (large caps)
    "RELIANCE": "Reliance Industries", "TCS": "Tata Consultancy Services",
    "HDFCBANK": "HDFC Bank", "ICICIBANK": "ICICI Bank", "INFY": "Infosys",
    "ITC": "ITC Limited", "SBIN": "State Bank of India",
    "KOTAKBANK": "Kotak Mahindra Bank", "AXISBANK": "Axis Bank",
    "LT": "Larsen & Toubro", "HINDUNILVR": "Hindustan Unilever",
    "BAJFINANCE": "Bajaj Finance", "MARUTI": "Maruti Suzuki",
    "ONGC": "Oil & Natural Gas Corp", "HCLTECH": "HCL Technologies",
    "SUNPHARMA": "Sun Pharmaceuticals", "ASIANPAINT": "Asian Paints",
    "NTPC": "NTPC Limited", "TITAN": "Titan Company",
    "ULTRACEMCO": "UltraTech Cement", "TATAMOTORS": "Tata Motors",
    "M&M": "Mahindra & Mahindra", "POWERGRID": "Power Grid Corp",
    "WIPRO": "Wipro", "BAJAJFINSV": "Bajaj Finserv",
    "NESTLEIND": "Nestle India", "COALINDIA": "Coal India",
    "TECHM": "Tech Mahindra", "JSWSTEEL": "JSW Steel",
    "ADANIPORTS": "Adani Ports & SEZ", "HINDALCO": "Hindalco Industries",
    "GRASIM": "Grasim Industries", "TATASTEEL": "Tata Steel",
    "INDUSINDBK": "IndusInd Bank", "SBILIFE": "SBI Life Insurance",
    "HDFCLIFE": "HDFC Life", "BRITANNIA": "Britannia Industries",
    "BAJAJ-AUTO": "Bajaj Auto", "APOLLOHOSP": "Apollo Hospitals",
    "DRREDDY": "Dr. Reddy's Laboratories", "CIPLA": "Cipla",
    "EICHERMOT": "Eicher Motors", "DIVISLAB": "Divi's Laboratories",
    "TATACONSUM": "Tata Consumer Products", "HEROMOTOCO": "Hero MotoCorp",
    "UPL": "UPL Limited", "BPCL": "Bharat Petroleum",
    "SHRIRAMFIN": "Shriram Finance", "ADANIENT": "Adani Enterprises",
    # Defence & PSU
    "BEL": "Bharat Electronics", "HAL": "Hindustan Aeronautics",
    "BDL": "Bharat Dynamics", "BEML": "BEML Limited", "BHEL": "Bharat Heavy Electricals",
    # Railways
    "IRCTC": "Indian Railway Catering & Tourism", "IRFC": "Indian Railway Finance Corp",
    "RVNL": "Rail Vikas Nigam", "RAILTEL": "RailTel Corp", "RITES": "RITES Limited",
    # PSU Banks
    "BANKBARODA": "Bank of Baroda", "PNB": "Punjab National Bank",
    "CANBK": "Canara Bank", "UNIONBANK": "Union Bank of India",
    "BANKINDIA": "Bank of India", "IOB": "Indian Overseas Bank",
    "CENTRALBANK": "Central Bank of India",
    # Private Banks
    "FEDERALBNK": "Federal Bank", "IDFCFIRSTB": "IDFC First Bank",
    "RBLBANK": "RBL Bank", "BANDHANBNK": "Bandhan Bank",
    "AUBANK": "AU Small Finance Bank", "DCBBANK": "DCB Bank",
    # FMCG
    "PIDILITIND": "Pidilite Industries", "DABUR": "Dabur India",
    "MARICO": "Marico", "COLPAL": "Colgate-Palmolive India",
    "GODREJCP": "Godrej Consumer Products", "EMAMILTD": "Emami",
    "BATAINDIA": "Bata India", "PAGEIND": "Page Industries",
    # IT / Software
    "COFORGE": "Coforge", "MPHASIS": "Mphasis", "PERSISTENT": "Persistent Systems",
    "LTTS": "L&T Technology Services", "TATAELXSI": "Tata Elxsi",
    "KPITTECH": "KPIT Technologies", "OFSS": "Oracle Financial Services",
    "CYIENT": "Cyient", "INFOEDGE": "Info Edge (Naukri)",
    "NAUKRI": "Info Edge (Naukri.com)",
    # Pharma
    "LUPIN": "Lupin", "AUROPHARMA": "Aurobindo Pharma",
    "BIOCON": "Biocon", "IPCALAB": "Ipca Laboratories",
    "ALKEM": "Alkem Laboratories", "GLENMARK": "Glenmark Pharmaceuticals",
    "GRANULES": "Granules India", "ZYDUSLIFE": "Zydus Lifesciences",
    "ABBOTINDIA": "Abbott India", "PFIZER": "Pfizer India",
    "LALPATHLAB": "Dr Lal PathLabs", "METROPOLIS": "Metropolis Healthcare",
    "GLAND": "Gland Pharma", "MANKIND": "Mankind Pharma",
    # Auto
    "TVSMOTOR": "TVS Motor Company", "ASHOKLEY": "Ashok Leyland",
    "ESCORTS": "Escorts Kubota", "BALKRISIND": "Balkrishna Industries",
    "MRF": "MRF", "CEATLTD": "CEAT", "APOLLOTYRE": "Apollo Tyres",
    "MOTHERSON": "Samvardhana Motherson", "MINDA": "Minda Industries",
    # Energy / Oil
    "GAIL": "GAIL India", "PETRONET": "Petronet LNG",
    "MGL": "Mahanagar Gas", "IGL": "Indraprastha Gas",
    "HINDPETRO": "Hindustan Petroleum", "MRPL": "MRPL",
    "ADANIGREEN": "Adani Green Energy", "ADANIPOWER": "Adani Power",
    "TATAPOWER": "Tata Power", "TORNTPOWER": "Torrent Power",
    # Metals
    "VEDL": "Vedanta", "SAIL": "Steel Authority of India",
    "NMDC": "NMDC", "HINDCOPPER": "Hindustan Copper",
    "HINDZINC": "Hindustan Zinc", "NATIONALUM": "National Aluminium",
    "JSPL": "Jindal Steel & Power",
    # Cement
    "RAMCOCEM": "The Ramco Cements", "JKCEMENT": "JK Cement",
    # Telecom
    "BHARTIARTL": "Bharti Airtel", "VODAIDEA": "Vodafone Idea",
    "TATACOMM": "Tata Communications",
    # Retail / E-commerce
    "DMART": "Avenue Supermarts (D-Mart)", "TRENT": "Trent",
    "NYKAA": "FSN E-Commerce (Nykaa)",
    "ZOMATO": "Zomato", "PAYTM": "One97 Communications (Paytm)",
    # Financial Services
    "RECLTD": "REC Limited", "PFC": "Power Finance Corp",
    "MUTHOOTFIN": "Muthoot Finance", "MANAPPURAM": "Manappuram Finance",
    "ICICIlombard": "ICICI Lombard GIC", "SBICARD": "SBI Cards",
    "CHOLAFIN": "Cholamandalam Investment",
    # Capital Markets
    "MCX": "Multi Commodity Exchange", "BSE": "BSE Limited",
    "CDSL": "CDSL", "CAMS": "Computer Age Management Services",
    # Chemicals
    "DEEPAKNITR": "Deepak Nitrite", "TATACHEM": "Tata Chemicals",
    "AARTIIND": "Aarti Industries", "NAVINFLUOR": "Navin Fluorine",
    "DEEPAKFERT": "Deepak Fertilisers", "COROMANDEL": "Coromandel International",
    # Real Estate
    "LODHA": "Macrotech Developers (Lodha)",
    "PRESTIGE": "Prestige Estates", "BRIGADE": "Brigade Enterprises",
    "SOBHA": "Sobha", "OBEROI": "Oberoi Realty",
    # Hospitals
    "FORTIS": "Fortis Healthcare", "MAXHEALTH": "Max Healthcare",
    "NARAYANA": "Narayana Hrudayalaya",
    # Infrastructure
    "NCC": "NCC Limited", "KEC": "KEC International",
    "KALPATPOWR": "Kalpataru Power",
    # FMCG / Consumer
    "BOSCHLTD": "Bosch India", "HAVELLS": "Havells India",
    "POLYCAB": "Polycab India", "VGUARD": "V-Guard Industries",
    "CROMPTON": "Crompton Greaves Consumer",
    "VOLTAS": "Voltas", "BLUESTAR": "Blue Star",
    # Logistics
    "CONCOR": "Container Corp of India",
    "DELHIVERY": "Delhivery",
    # Media
    "SUNTV": "Sun TV Network", "PVRINOX": "PVR Inox",
    # Miscellaneous
    "INDIGO": "InterGlobe Aviation (IndiGo)",
    "JUSTDIAL": "Just Dial",
    "CRISIL": "CRISIL",
    "BERGEPAINT": "Berger Paints",
    "GODREJPROP": "Godrej Properties",
    "TORNTPHARM": "Torrent Pharmaceuticals",
    "APLAPOLLO": "APL Apollo Tubes",
    "ASTRAL": "Astral",
    "IREDA": "Indian Renewable Energy Dev Agency",
    "SJVN": "SJVN Limited",
    "NHPC": "NHPC Limited",
    "ATGL": "Adani Total Gas",
    "GSPL": "Gujarat State Petronet",
    "EXIDEIND": "Exide Industries",
    "SAREGAMA": "Saregama India",
    "SUPRAJIT": "Suprajit Engineering",
    "GREAVESCOT": "Greaves Cotton",
    "ELGIEQUIP": "Elgi Equipments",
    "SCHAEFFLER": "Schaeffler India",
    "TIMKEN": "Timken India",
    "ABB": "ABB India",
    "SIEMENS": "Siemens India",
    "CUMMINSIND": "Cummins India",
    "THERMAX": "Thermax",
    "HONAUT": "Honeywell Automation India",
    "MINDAIND": "Minda Industries",
    "GABRIEL": "Gabriel India",
    "TIINDIA": "Tube Investments of India",
    "FORCEMOT": "Force Motors",
    "TEAMLEASE": "TeamLease Services",
    "QUESS": "Quess Corp",
    "INDIABULLS": "Indiabulls Housing Finance",
    "LICHOUSING": "LIC Housing Finance",
    "SIS": "SIS Limited",
    "GILLETTE": "Gillette India",
    "RAYMOND": "Raymond",
    "WELSPUN": "Welspun India",
    "VMART": "V-Mart Retail",
    "DELTACORP": "Delta Corp",
    "TANLA": "Tanla Platforms",
    "HFCL": "HFCL Limited",
    "MKPL": "Market Pay (MCX)",
    "SBFC": "SBFC Finance",
    "PAISALO": "Paisalo Digital",
    "5PAISA": "5Paisa Capital",
    "MOTILALOFS": "Motilal Oswal Financial Services",
    "EQUITASBNK": "Equitas Small Finance Bank",
    "SURYODAY": "Suryoday Small Finance Bank",
    "UTKARSHBNK": "Utkarsh Small Finance Bank",
    "GREENPLY": "Greenply Industries",
    "CENTURYPLY": "Century Plyboards",
    "AARTIDRUGS": "Aarti Drugs",
    "MARKSANS": "Marksans Pharma",
    "INDIAMART": "IndiaMART InterMESH",
    "CAMPUSACT": "Campus Activewear",
    "ALLCARGO": "Allcargo Logistics",
    "INDIACEM": "The India Cements",
    "HERITGFOOD": "Heritage Foods",
    "JUGAADU": "Jugadu Kamlesh",
    "JSWENERGY": "JSW Energy",
    "NAZARA": "Nazara Technologies",
    "MAPMYINDIA": "C.E. Info Systems (MapmyIndia)",
    "SWIGGY": "Bundl Technologies (Swiggy)",
    "SYNGENE": "Syngene International",
}
